config/routes.rb
Rails.application.routes.draw do
  resources :racers do
    post "entries" => "racers#create_entry"
  end
  resources :races

end

app/models/race.rb
class Race
  include Mongoid::Document
  include Mongoid::Timestamps

  field :next_bib, as: :next_bib, type: Integer, default: 0
  field :n, as: :name, type: String
  field :date, as: :date, type: Date
  field :loc, as: :location, type: Address

  embeds_many :events, as: :parent, order: [:order.asc]
  has_many :entrants,
            class_name: 'Entrant',
            foreign_key: "race._id",
            order: [:secs.asc, :bib.asc],
            dependent: :delete

  scope :upcoming, -> { where(:date => {:$gte => Date.current}) }
  scope :past, -> { where(:date => {:$lt => Date.current}) }

  #example of default events for race
  DEFAULT_EVENTS = {"swim"=>{:order=>0, :name=>"swim", :distance=>1.0, :units=>"miles"},
                  "t1"=>  {:order=>1, :name=>"t1"},
                  "bike"=>{:order=>2, :name=>"bike", :distance=>25.0, :units=>"miles"},
                  "t2"=>  {:order=>3, :name=>"t2"},
                  "run"=> {:order=>4, :name=>"run", :distance=>10.0, :units=>"kilometers"}}

  #adds through meta methods for default events
  DEFAULT_EVENTS.keys.each do |name|
    define_method("#{name}") do
      event=events.select {|event| name==event.name}.first
      event||=events.build(DEFAULT_EVENTS["#{name}"])
    end

    ["order","distance","units"].each do |prop|
      if DEFAULT_EVENTS["#{name}"][prop.to_sym]
        define_method("#{name}_#{prop}") do
          event=self.send("#{name}").send("#{prop}")
        end
        define_method("#{name}_#{prop}=") do |value|
          event=self.send("#{name}").send("#{prop}=", value)
        end
      end
    end
  end

  #invokes through meta the creation of default events defined in DEFAULT_EVENTS
  def Race.default
    Race.new do |race|
      DEFAULT_EVENTS.keys.each {|leg|race.send("#{leg}")}
    end
  end

  def Race.upcoming_available_to(racer)
    upcoming_race_ids = racer.races.upcoming.pluck(:race).map {|r| r[:_id]}
    Race.upcoming.nin(id: upcoming_race_ids)
  end

  #adds through meta city and state accessors
  ["city", "state"].each do |action|
    define_method("#{action}") do
      self.location ? self.location.send("#{action}") : nil
    end
    define_method("#{action}=") do |name|
      object=self.location ||= Address.new
      object.send("#{action}=", name)
      self.location=object
    end
  end

  def next_bib
    self[:next_bib] += 1
    save
    self[:next_bib]
  end

  def get_group(racer)
    if racer && racer.birth_year && racer.gender
      quotient = (date.year-racer.birth_year) / 10
      min_age = quotient*10
      max_age = ((quotient+1)*10)-1
      gender = racer.gender
      name = min_age >= 60 ? "masters #{gender}" : "#{min_age} to #{max_age} (#{gender})"
      Placing.demongoize(:name=>name)
    end
  end

  def create_entrant(racer)
    entrant = Entrant.new

    entrant.build_race(self.attributes.symbolize_keys.slice(:_id, :n, :date))

    entrant.build_racer(racer.info.attributes)

    # entrant.first_name = racer.first_name
    # entrant.last_name = racer.last_name
    # entrant.gender = racer.gender
    # entrant.birth_year = racer.birth_year

    entrant.group = get_group(racer)

    events.each do |event|
      entrant.send("#{event.name}=", event)
    end

    if entrant.validate
      entrant.bib = next_bib
      entrant.save
    end
    entrant
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]

  # GET /races
  # GET /races.json
  def index
    @races = Race.all.order(date: :desc)
  end

  # GET /races/1
  # GET /races/1.json
  def show
    @entrants=Entrant.where(:"race._id"=>@race.id).order(overall: :asc, last_name: :asc, first_name: :asc)
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Race was successfully created.' }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: 'Race was successfully updated.' }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: 'Race was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params.require(:race).permit(:name, :date, :city, :state, :swim_distance, :swim_units, :bike_distance, :bike_units, :run_distance, :run_units)
    end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<%= form_for(@race) do |f| %>
  <% if @race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
      <% @race.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :swim_distance %><br>
    <%= f.text_field :swim_distance %>
  </div>
  <div class="field">
    <%= f.label :swim_units %><br>
    <%= f.text_field :swim_units %>
  </div>
  <div class="field">
    <%= f.label :bike_distance %><br>
    <%= f.text_field :bike_distance %>
  </div>
  <div class="field">
    <%= f.label :bike_units %><br>
    <%= f.text_field :bike_units %>
  </div>
  <div class="field">
    <%= f.label :run_distance %><br>
    <%= f.text_field :run_distance %>
  </div>
  <div class="field">
    <%= f.label :run_units %><br>
    <%= f.text_field :run_units %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/races/edit.html.erb
<h1>Editing Race</h1>

<%= render 'form' %>

<%= link_to 'Show', @race %> |
<%= link_to 'Back', races_path %>

app/views/races/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Races</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>City</th>
      <th>State</th>
      <th>Swim distance</th>
      <th>Swim units</th>
      <th>Bike distance</th>
      <th>Bike units</th>
      <th>Run distance</th>
      <th>Run units</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race.name %></td>
        <td><%= race.date %></td>
        <td><%= race.city %></td>
        <td><%= race.state %></td>
        <td><%= race.swim_distance %></td>
        <td><%= race.swim_units %></td>
        <td><%= race.bike_distance %></td>
        <td><%= race.bike_units %></td>
        <td><%= race.run_distance %></td>
        <td><%= race.run_units %></td>
        <td><%= link_to 'Show', race %></td>
        <td><%= link_to 'Edit', edit_race_path(race) %></td>
        <td><%= link_to 'Destroy', race, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Race', new_race_path %>

app/views/races/new.html.erb
<h1>New Race</h1>

<%= render 'form' %>

<%= link_to 'Back', races_path %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @race.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @race.date %>
</p>

<p>
  <strong>City:</strong>
  <%= @race.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @race.state %>
</p>

<p>
  <strong>Swim distance:</strong>
  <%= @race.swim_distance %>
</p>

<p>
  <strong>Swim units:</strong>
  <%= @race.swim_units %>
</p>

<p>
  <strong>Bike distance:</strong>
  <%= @race.bike_distance %>
</p>

<p>
  <strong>Bike units:</strong>
  <%= @race.bike_units %>
</p>

<p>
  <strong>Run distance:</strong>
  <%= @race.run_distance %>
</p>

<p>
  <strong>Run units:</strong>
  <%= @race.run_units %>
</p>

<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'Back', races_path %>

</p><strong>Results:</strong>
<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Time</th>
      <th>Name</th>

      <th>Bib#</th>
      <th>City</th>
      <th>State</th>
      <th>Gender</th>
      <th>Gender Place</th>
      <th>Group</th>
      <th>Group Place</th>
      <th>Swim</th>
      <th>Pace 100</th>
      <th>T1</th>
      <th>Bike</th>
      <th>MPH</th>
      <th>T2</th>

      <th>Run</th>
      <th>Min Mile</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @entrants.each do |entrant| %>
      <tr>
        <td><%= entrant.overall_place %></td>
        <td><%= format_hours entrant.secs %></td>
        <% if entrant.racer.id %>
          <td><%= link_to "#{entrant.last_name}, #{entrant.first_name}", racer_path(entrant.racer.id) %>
        <% else %>
          <td><%= "#{entrant.last_name}, #{entrant.first_name}" %></td>
        <% end %>

        <td><%= entrant.bib %></td>
        <td><%= entrant.city %></td>
        <td><%= entrant.state %></td>
        <td><%= entrant.racer_gender %></td>
        <td><%= entrant.gender_place %></td>
        <td><%= entrant.group_name %></td>
        <td><%= entrant.group_place %></td>
        <td><%= format_hours(entrant.swim_secs) %></td>
        <td><%= format_minutes(entrant.swim_pace_100) %></td>
        <td><%= format_minutes(entrant.t1_secs) %></td>
        <td><%= format_hours(entrant.bike_secs) %></td>
        <td><%= format_mph(entrant.bike_mph) %></td>
        <td><%= format_minutes(entrant.t2_secs) %></td>

        <td><%= format_hours entrant.run_secs %></td>
        <td><%= format_minutes entrant.run_mmile %></td>
      </tr>
    <% end %>
  </tbody>
</table>