config/routes.rb
Rails.application.routes.draw do
  resources :racers do
    post "entries" => "racers#create_entry"
  end
  resources :races

end

app/models/racer.rb
class Racer
  include Mongoid::Document

  delegate :first_name, :first_name=, to: :info
  delegate :last_name, :last_name=, to: :info
  delegate :gender, :gender=, to: :info
  delegate :birth_year, :birth_year=, to: :info
  delegate :city, :city=, to: :info
  delegate :state, :state=, to: :info

  embeds_one :info, class_name: 'RacerInfo', as: :parent, autobuild: true
  has_many :races, class_name: 'Entrant',
                   foreign_key: "racer.racer_id",
                   dependent: :nullify,
                   order: :"race.date".desc

  before_create do |racer|
    racer.info.id = racer.id
  end
end

app/controllers/racers_controller.rb
class RacersController < ApplicationController
  before_action :set_racer, only: [:show, :edit, :update, :destroy]

  # GET /racers
  # GET /racers.json
  def index
    @racers = Racer.all
  end

  # GET /racers/1
  # GET /racers/1.json
  def show
    @races = @racer.races
  end

  # GET /racers/new
  def new
    @racer = Racer.new
  end

  # GET /racers/1/edit
  def edit
    @races = Race.upcoming_available_to(@racer).order_by(:date.asc)
  end

  # POST /racers
  # POST /racers.json
  def create
    @racer = Racer.new(racer_params)

    respond_to do |format|
      if @racer.save
        format.html { redirect_to @racer, notice: 'Racer was successfully created.' }
        format.json { render :show, status: :created, location: @racer }
      else
        format.html { render :new }
        format.json { render json: @racer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /racers/1
  # PATCH/PUT /racers/1.json
  def update
    respond_to do |format|
      if @racer.update(racer_params)
        format.html { redirect_to @racer, notice: 'Racer was successfully updated.' }
        format.json { render :show, status: :ok, location: @racer }
      else
        format.html { render :edit }
        format.json { render json: @racer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /racers/1
  # DELETE /racers/1.json
  def destroy
    @racer.destroy
    respond_to do |format|
      format.html { redirect_to racers_url, notice: 'Racer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_entry
    @racer = Racer.find(params[:racer_id])
    @race = Race.find(params[:race_id])
    @entrant = @race.create_entrant(@racer)

    respond_to do |format|
      if @entrant.valid?
        format.html { redirect_to @racer, notice: 'Race entry was successfully created.' }
        format.json { render :show, status: :created, location: @racer }
      else
        format.html { redirect_to @racer, notice: "Invalid registration #{@entrant.errors.messages}" }
        format.json { render json: @entrant.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_racer
      @racer = Racer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def racer_params
      params.require(:racer).permit(:first_name, :last_name, :gender, :birth_year, :city, :state)
    end
end

app/helpers/racers_helper.rb
module RacersHelper
end

app/views/racers/_form.html.erb
<%= form_for(@racer) do |f| %>
  <% if @racer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@racer.errors.count, "error") %> prohibited this racer from being saved:</h2>

      <ul>
      <% @racer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :birth_year %><br>
    <%= f.text_field :birth_year %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% if @racer.persisted? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Date</th>
        <th>City</th>

        <th>State</th>
        <th>Swim</th>
        <th>units</th>
        <th>Bike</th>
        <th>units</th>

        <th>Run distance</th>
        <th>Run units</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @races.each do |race| %>
        <tr>
          <td><%= race.name %></td>
          <td><%= race.date %></td>
          <td><%= race.city %></td>

          <td><%= race.state %></td>
          <td><%= race.swim_distance %></td>
          <td><%= race.swim_units %></td>
          <td><%= race.bike_distance %></td>
          <td><%= race.bike_units %></td>

          <td><%= race.run_distance %></td>
          <td><%= race.run_units %></td>
          <td><%= link_to 'Register', racer_entries_path(@racer, :race_id=>race.id), method: :post %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/racers/edit.html.erb
<h1>Editing Racer</h1>

<%= render 'form' %>

<%= link_to 'Show', @racer %> |
<%= link_to 'Back', racers_path %>

app/views/racers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Racers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Birth year</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @racers.each do |racer| %>
      <tr>
        <td><%= racer.first_name %></td>
        <td><%= racer.last_name %></td>
        <td><%= racer.gender %></td>
        <td><%= racer.birth_year %></td>
        <td><%= racer.city %></td>
        <td><%= racer.state %></td>
        <td><%= link_to 'Show', racer %></td>
        <td><%= link_to 'Edit', edit_racer_path(racer) %></td>
        <td><%= link_to 'Destroy', racer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Racer', new_racer_path %>

app/views/racers/new.html.erb
<h1>New Racer</h1>

<%= render 'form' %>

<%= link_to 'Back', racers_path %>

app/views/racers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @racer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @racer.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @racer.gender %>
</p>

<p>
  <strong>Birth year:</strong>
  <%= @racer.birth_year %>
</p>

<p>
  <strong>City:</strong>
  <%= @racer.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @racer.state %>
</p>

<%= link_to 'Edit', edit_racer_path(@racer) %> |
<%= link_to 'Back', racers_path %>

</p>
<strong>Races:</strong>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Overall Place</th>
      <th>Gender Place</th>
      <th>Group Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @races.each do |entry| %>
      <tr>
        <td><%= entry.race_name %></td>
        <td><%= entry.race_date %></td>
        <td><%= entry.overall_place %></td>
        <td><%= entry.gender_place %></td>
        <td><%= entry.group_place %></td>
        <td><%= link_to 'Results', race_path(entry.race) %></td>
      </tr>
    <% end %>
  </tbody>
<table>